apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: fsw-sample-app
    app.kubernetes.io/part-of: fsw-sample-app
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: sample-app
