---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  database-type: mysql
  database-host: mariadb-sample
  database-port-number: '3306'
  database-name: sample-database
  oidc-provider-url: https://login.acc.uu.nl/nidp/oauth/nam
  oidc-slo-link: https://login.acc.uu.nl/nidp/app/logout
  vite-api-url: app.openshift.fss.uu.nl
  vite-port: '7050'