apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsw-sample-front
  labels:
    app: fsw-sample-app
    app.kubernetes.io/part-of: fsw-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-front
  template:
    metadata:
      labels:
        app: sample-front
    spec:
      containers:
        - name: sample-front
          image: ghcr.io/utrechtuniversity/fsw-openshift-frontend:develop
          ports:
            - containerPort: 7050
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: sample-frontend-config
                  key: vite-api-url
            - name: VITE_PORT
              valueFrom:
                configMapKeyRef:
                  name: sample-frontend-config
                  key: vite-port
